### ISSUE TITLE
OJN volume panning byte [facepalm]

### ISSUE THREAD

**Issue by keigen-shu** [open2jamorg/open2jam#12]
[facepalm]. It took me months to figure this out. Here's the fix for it:

Proof: http://s12.postimage.org/3p6owfjq5/OJN.png

``` c++
// Original
// float Vol = (volume_pan & 0xF) / 16f;
// float Pan = (volume_pan & 0xF0) >> 4;
float Vol = (float)((VolPan >> 4) & 0x0F); // higher half
float Pan = (float) (VolPan & 0x0F);       //  lower half

if (Vol == 0) Vol = 1.0f;
else Vol = (Vol / 16.0f);

if (Pan == 0) Pan = 0.0f;
else Pan = (Pan -  8.0f) / 8.0f;
```

EDIT: Here's the legend.

```
VolPan byte Legend
Value in Note Tool = Value in OJN File = Resultant Value

For Volume:
 1 = 0x10 =  1/16 MIN
 2 = 0x20 =  2/16
 3 = 0x30 =  3/16
 4 = 0x40 =  4/16
 5 = 0x50 =  5/16
 6 = 0x60 =  6/16
 7 = 0x70 =  7/16
 8 = 0x80 =  8/16
 9 = 0x90 =  9/16
10 = 0xA0 = 10/16
11 = 0xB0 = 11/16
12 = 0xC0 = 12/16
13 = 0xD0 = 13/16
14 = 0xE0 = 14/16
15 = 0xF0 = 15/16
16 = 0x00 = 16/16 MAX

For Panning:
     0x08 ---- unused. assume center.
 1 = 0x01 = 7L
 2 = 0x02 = 6L
 3 = 0x03 = 5L
 4 = 0x04 = 4L
 5 = 0x05 = 3L
 6 = 0x06 = 2L
 7 = 0x07 = 1L
 8 = 0x00 = 0C
 9 = 0x09 = 1R
10 = 0x0A = 2R
11 = 0x0B = 3R
12 = 0x0C = 4R
13 = 0x0D = 5R
14 = 0x0E = 6R
15 = 0x0F = 7R
```

**Comment by mrcdk** [comment]
OMFG, you're right xD. All chaosfox fault btw :D

One thing I've found:
Pan = (Pan-8) / 8f; shouldn't be 7f? (15-8) / 8 = 7 / 8 = 0.875 and it should be 1, right?
I'm not sure because openAL [has not 2D panning support](http://connect.creativelabs.com/openal/Lists/Wishlist/DispForm.aspx?ID=18) srly, wtf ·-. Good thing we are thinking into moving to bass or fmod xD

**Comment by keigen-shu** [comment]
I'm not sure how it's implemented on O2Jam. I tested this on the official NoteTool (vilin's) and when Pan is set to 15, there is a slight sound residue on the left side and vice versa. Thus, I came to the conclusion that it's not hard-panned and left it as

``` c++
Pan = (Pan - 8) / 8.0f; // not hard-panned
```

**Comment by mrcdk** [comment]
OK, I will close this issue then
