### ISSUE TITLE
Release notes in autoplay lane

### ISSUE THREAD

**Issue by keigen-shu** [open2jamorg/open2jam#13]
There are cases where a long note's release can end up in the autoplay lanes. Try playing Brahms(O2 Remix)+ on HX. You can hear the double keysounds just as if they were long notes. I guess it surfaced beause Beautiful Day was a lazy notecharter (and mixer) and the NoteTool was just recently upgraded then to support long notes and had this design error.

Fix:

``` java
else if (type == 3 && channel != Event.Channel.AUTO_PLAY) {
    event_list.add(new Event(channel, measure, position, value, Event.Flag.RELEASE, volume, pan));
}
```

**Comment by chaosfox** [comment]
OH that's it !

I always noticed that but never realized the problem !, thanks.

**Comment by mrcdk** [comment]
Omg, I forgot about this xD I think it's [fixed now](https://github.com/chaosfox/open2jam/commit/00b5bf30d212507781f960fea139012cf9fdea17) right?
