### ISSUE TITLE
Fix for longflare animation

### ISSUE THREAD

**Issue by hirandom** [open2jamorg/open2jam#17]
Btw, if this already hasn't been fixed, a rather (IMO inelegent) workaround for the longflare animation can be achieved by keeping track of which entities are longflares ( i.e. add a public boolean isLongFlare to the Entity class, with default value as false. ) Then in the DistanceRenderer and TimeRenderer, immediately before these lines:

entities_matrix.add(ee);
Entity to_kill = longflare.put(ne.getChannel(),ee);
if(to_kill != null)to_kill.setDead(true);

add the line:

ee.isLongFlare = true;

Again in the Entity class,
add the following at the top:

import org.lwjgl.opengl.GL11;

and replace the draw function with:

if ( isLongFlare ){ GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_DST_ALPHA); }
sprite.draw(x,y, sprite.getScaleX(), sprite.getScaleY());
if ( isLongFlare ){ GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA); }

**Comment by mrcdk** [comment]
umm... what is the longflare animation bug? xD

Anyway, don't worry about the graphical part, we are waiting [libGDX](http://code.google.com/p/libgdx/) team to release a new version of their library to work with it. It will abstract us from the ogl pain and it's really easy to work with. Also we'll be able to compile for android and, hopefully, webGL. Also I'm think to use the bass lib for the audio for windows, linux and mac os. So, don't worry about it, we'll be working on it soon :D

**Comment by chaosfox** [comment]
shame on me for not noticing this before
now we just need to figure out which entities exactly use alpha blending
I submitted a fix that adds alpha blend on the long flare and on note hit
