### ISSUE TITLE
Keyboard handling does not work on Mac

### ISSUE THREAD

**Issue by dtinth** [open2jamorg/open2jam#5]
On Mac OS X, open2jam seems to not be able to handle any key presses, instead, the program freezes.

It does not crash, it just doesn't respond to user events anymore.

For example, when playing a song, the notes will drop just fine, but you can't press any keys. You can't close the window either. The same also happens on keyboard configuration screen, after you click on a row and a dialog box pops up, the app freezes too.

**Comment by mrcdk** [comment]
Well, that will be pretty hard to fix because I think  none of us have a mac xD Last time open2jam was tested on one the only problem was that it wasn't handling the esc key but other things were ok :/ And as far as i know the keyboard handling hasn't being touched after that.

**Comment by chaosfox** [comment]
@dtinth Is this a regression ? I mean, this is the first time you are testing or did it worked in previous versions ?

Edit: this is probably the problem http://lwjgl.org/forum/index.php/topic,3660.0.html

**Comment by dtinth** [comment]
It didn't work since the first time I tried it on Mac OS X, and that was since alpha 5.

And yes the third post in that link does make sense.

**Comment by chaosfox** [comment]
I made the render execute on a separate thread on branch keyboard_mac, now we need to test it somehow, if I make you a build can you test it ?

**Comment by dtinth** [comment]
Yes. That would be very convenient for me.

I'm actually trying to download NetBeans here, but that's gonna take some time, so a build would be cool :D.

**Comment by chaosfox** [comment]
here: https://github.com/downloads/chaosfox/open2jam/open2jam_keyboardmac.zip
thats only the jar actually, just replace with the other one, the rest doesn't change.

**Comment by dtinth** [comment]
Yes, it works. Awesome!

Thanks. :)

**Comment by chaosfox** [comment]
Solved then ! thank you for reporting the bug.
