### ISSUE TITLE
handle config class changes

### ISSUE THREAD

**Issue by chaosfox** [open2jamorg/open2jam#7]
When a serializable class definition is modified the serialVersionUID changes and with that when you try to de-serialize an object of an older version a java.io.InvalidClassException is thrown in Config.get(). That means the object is unusable and the config is lost.
Right now this happens when we change the GameOptions definition since it's the only custom class we serialize now. But it could happen with others on the future if we serialize them too.

Proposed solution:
Define a fixed serialVersionUID for custom serialized classes and every time the class is changed test the serialization, in case of incompatibility, increment the serialVersionUID, then on Config.get() catch the InvalidClassException, now when it happens it means there is no other way than to recreate the object with the default and save that.

**Comment by dtinth** [comment]
We used XMLEncoder and XMLDecoder to store game options now, this problem should be fixed.

However, this only applies to game options. We'll have to look about the Config class itself later, but now, there shouldn't be problems adding more options to the GameOptions class.
